-- 已有库增量执行；不会修改题型图片或发布版本。
CREATE TABLE IF NOT EXISTS t_image_generation_task (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键',
    request_id CHAR(36) NOT NULL COMMENT '请求幂等 UUID',
    test_id BIGINT UNSIGNED NOT NULL COMMENT '关联题型',
    operator_id BIGINT UNSIGNED NOT NULL COMMENT '创建人',
    provider TINYINT NOT NULL COMMENT '1千问，2火山',
    model_name VARCHAR(128) NOT NULL COMMENT '模型快照',
    endpoint VARCHAR(500) NOT NULL COMMENT 'API地址快照，无密钥',
    region VARCHAR(64) NULL COMMENT '区域快照',
    prompt_text VARCHAR(1500) NOT NULL COMMENT '运营关键词',
    cover_prompt TEXT NOT NULL COMMENT '封面最终提示词',
    detail_prompt TEXT NOT NULL COMMENT '详情最终提示词',
    cover_width INT NOT NULL DEFAULT 800 COMMENT '封面最终宽度像素',
    cover_height INT NOT NULL DEFAULT 800 COMMENT '封面最终高度像素',
    detail_width INT NOT NULL DEFAULT 1100 COMMENT '详情最终宽度像素',
    detail_height INT NOT NULL DEFAULT 500 COMMENT '详情最终高度像素',
    cover_task_id VARCHAR(256) NULL COMMENT '封面上游任务编号',
    detail_task_id VARCHAR(256) NULL COMMENT '详情上游任务编号',
    cover_submission_started TINYINT NOT NULL DEFAULT 0 COMMENT '封面已发起提交',
    detail_submission_started TINYINT NOT NULL DEFAULT 0 COMMENT '详情已发起提交',
    cover_url VARCHAR(500) NULL COMMENT '转存封面图地址',
    detail_image_url VARCHAR(500) NULL COMMENT '转存详情图地址',
    task_status TINYINT NOT NULL DEFAULT 1 COMMENT '1排队2生成3成功4失败5已采用',
    error_message VARCHAR(1000) NULL COMMENT '失败原因',
    applied_version_id BIGINT UNSIGNED NULL COMMENT '采用后草稿版本',
    completed_at DATETIME NULL COMMENT '生成完成时间',
    applied_at DATETIME NULL COMMENT '采用时间',
    deleted TINYINT NOT NULL DEFAULT 0 COMMENT '0正常1删除',
    create_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    active_test_id BIGINT UNSIGNED GENERATED ALWAYS AS
        (CASE WHEN deleted = 0 AND task_status IN (1, 2) THEN test_id ELSE NULL END) STORED,
    PRIMARY KEY (id),
    UNIQUE KEY uk_image_task_request (request_id),
    UNIQUE KEY uk_image_task_active_test (active_test_id),
    KEY idx_image_task_test (test_id, deleted, id),
    CONSTRAINT chk_image_task_provider CHECK (provider IN (1, 2)),
    CONSTRAINT chk_image_task_status CHECK (task_status BETWEEN 1 AND 5)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='AI封面详情双图任务';
